-- 해안 산책을 '해안 산책'과 '해수욕장'으로 분리 — BEACH 값 추가

-- AlterTable
ALTER TABLE `leisure_candidates` MODIFY `suggested_activity` ENUM('YACHT', 'CRUISE', 'PADDLE_BOAT', 'MUDFLAT', 'COASTAL_WALK', 'BEACH', 'TREKKING', 'CYCLING', 'CAMPING', 'BACKPACKING', 'FISHING', 'PULDEUNG', 'NIGHT_GATHERING', 'ZIPLINE', 'MONORAIL', 'LUGE', 'GOLF', 'GROUP_TRAINING', 'FOREST_BATH', 'SUNSET', 'SEAL_WATCHING', 'STARGAZING', 'VILLAGE_TOUR', 'SPA', 'ETC') NULL;

-- AlterTable
ALTER TABLE `leisure_sports` MODIFY `activity` ENUM('YACHT', 'CRUISE', 'PADDLE_BOAT', 'MUDFLAT', 'COASTAL_WALK', 'BEACH', 'TREKKING', 'CYCLING', 'CAMPING', 'BACKPACKING', 'FISHING', 'PULDEUNG', 'NIGHT_GATHERING', 'ZIPLINE', 'MONORAIL', 'LUGE', 'GOLF', 'GROUP_TRAINING', 'FOREST_BATH', 'SUNSET', 'SEAL_WATCHING', 'STARGAZING', 'VILLAGE_TOUR', 'SPA', 'ETC') NOT NULL;

