-- 레저 활동 enum 을 현재 분류(프론트 종목 23개)와 동기화
--   추가: YACHT(요트)
--   제거: KAYAK(카약), SURFING(서핑) — 인천 앞바다 조건상 운영처 없음
--   두 테이블 모두 0행 상태에서 적용

-- AlterTable
ALTER TABLE `leisure_candidates` MODIFY `suggested_activity` ENUM('YACHT', 'CRUISE', 'PADDLE_BOAT', 'MUDFLAT', 'COASTAL_WALK', 'TREKKING', 'CYCLING', 'CAMPING', 'BACKPACKING', 'FISHING', 'PULDEUNG', 'NIGHT_GATHERING', 'ZIPLINE', 'MONORAIL', 'LUGE', 'GOLF', 'GROUP_TRAINING', 'FOREST_BATH', 'SUNSET', 'SEAL_WATCHING', 'STARGAZING', 'VILLAGE_TOUR', 'SPA', 'ETC') NULL;

-- AlterTable
ALTER TABLE `leisure_sports` MODIFY `activity` ENUM('YACHT', 'CRUISE', 'PADDLE_BOAT', 'MUDFLAT', 'COASTAL_WALK', 'TREKKING', 'CYCLING', 'CAMPING', 'BACKPACKING', 'FISHING', 'PULDEUNG', 'NIGHT_GATHERING', 'ZIPLINE', 'MONORAIL', 'LUGE', 'GOLF', 'GROUP_TRAINING', 'FOREST_BATH', 'SUNSET', 'SEAL_WATCHING', 'STARGAZING', 'VILLAGE_TOUR', 'SPA', 'ETC') NOT NULL;

