export type IslandInfo = {
  id: string;
  name: string;
  region: string;
  visited: boolean;
  intro: string;
  leisureCourses: string[];
  ferryRoute: string;
  travelTime: string;
  bookingLabel?: string;
};

export const ISLANDS: IslandInfo[] = [
  {
    id: "baek",
    name: "백령도",
    region: "백령·대청도권역",
    visited: true,
    intro: "서해 최북단의 청정 섬으로 두무진 해안과 사곶해안이 유명합니다. 자전거 일주와 해안 트레킹이 인기입니다.",
    leisureCourses: ["두무진 해안 트레킹", "사곶해안 사이클", "등대 전망 포인트"],
    ferryRoute: "인천항 ↔ 백령도",
    travelTime: "약 4시간 30분",
    bookingLabel: "레저 예약하기",
  },
  {
    id: "daech",
    name: "대청도",
    region: "백령·대청도권역",
    visited: false,
    intro: "백령도와 함께 서해 북부권을 이루는 섬으로 조용한 해안 산책과 낚시 포인트가 많습니다.",
    leisureCourses: ["해안 산책로", "갯바위 낚시", "일몰 포토 스팟"],
    ferryRoute: "백령도 ↔ 대청도",
    travelTime: "약 40분",
  },
  {
    id: "yeonp",
    name: "연평도",
    region: "연평도권역",
    visited: false,
    intro: "군사 분계선 인근의 섬으로 맑은 바다와 해안 절경이 아름다운 탐험지입니다.",
    leisureCourses: ["연평 해안 둘레길", "스노클링", "섬 일주 드라이브"],
    ferryRoute: "인천항 ↔ 연평도",
    travelTime: "약 2시간 30분",
  },
  {
    id: "gangh",
    name: "강화도",
    region: "강화도권역",
    visited: false,
    intro: "인천에서 가장 가까운 대형 섬으로 역사 유적과 갯벌 체험, 해안 사이클이 풍부합니다.",
    leisureCourses: ["강화 해안 사이클", "갯벌 체험", "전등사·길상사 문화 탐방"],
    ferryRoute: "인천항 ↔ 강화도",
    travelTime: "약 1시간 10분",
    bookingLabel: "레저 예약하기",
  },
  {
    id: "gyo",
    name: "교동도",
    region: "강화도권역",
    visited: false,
    intro: "강화도 인근의 작은 섬으로 조용한 해변과 어촌 마을 풍경을 즐길 수 있습니다.",
    leisureCourses: ["마을 산책", "낚시", "일출 감상"],
    ferryRoute: "강화도 ↔ 교동도",
    travelTime: "약 25분",
  },
  {
    id: "seok",
    name: "석모도",
    region: "강화도권역",
    visited: false,
    intro: "강화 남부의 섬으로 바위 해안과 등대 전망이 인상적인 레저 스팟입니다.",
    leisureCourses: ["등대 전망대", "해안 트레킹", "카약"],
    ferryRoute: "강화도 ↔ 석모도",
    travelTime: "약 30분",
  },
  {
    id: "jang",
    name: "장봉도",
    region: "북도권역",
    visited: false,
    intro: "갯벌 체험과 가족 단위 레저에 적합한 섬으로 얕은 바다가 특징입니다.",
    leisureCourses: ["갯벌 체험", "패밀리 피크닉", "조개 잡기"],
    ferryRoute: "인천항 ↔ 장봉도",
    travelTime: "약 1시간 40분",
  },
  {
    id: "sinsi",
    name: "신도·시도·모도",
    region: "북도권역",
    visited: true,
    intro: "세 섬이 연결된 자전거 길이 유명한 탐험 코스로 평지 라이딩에 최적입니다.",
    leisureCourses: ["신도-시도-모도 사이클", "해안 산책", "섬 마을 탐방"],
    ferryRoute: "인천항 ↔ 신도",
    travelTime: "약 1시간 20분",
    bookingLabel: "레저 예약하기",
  },
  {
    id: "yeongj",
    name: "영종도",
    region: "영종구·서해구권역",
    visited: true,
    intro: "인천국제공항이 있는 섬으로 해안 사이클과 왕산해수욕장이 대표 레저입니다.",
    leisureCourses: ["왕산 해수욕장", "해안 사이클", "을왕리 노을 코스"],
    ferryRoute: "인천항 ↔ 영종도",
    travelTime: "약 40분",
    bookingLabel: "레저 예약하기",
  },
  {
    id: "muui",
    name: "무의도",
    region: "영종구·서해구권역",
    visited: true,
    intro: "하나개 해수욕장과 무의바다누리길로 유명한 서해 레저의 대표 섬입니다.",
    leisureCourses: ["카약 · SUP", "무의바다누리길 러닝", "하나개 해수욕장"],
    ferryRoute: "영종도 ↔ 무의도",
    travelTime: "약 15분",
    bookingLabel: "레저 예약하기",
  },
  {
    id: "yheung",
    name: "영흥도",
    region: "영흥도권역",
    visited: false,
    intro: "서해 남부의 대형 섬으로 해안 드라이브와 낚시, 캠핑이 인기입니다.",
    leisureCourses: ["해안 드라이브", "방파제 낚시", "캠핑"],
    ferryRoute: "인천항 ↔ 영흥도",
    travelTime: "약 2시간",
  },
  {
    id: "jawol",
    name: "자월도",
    region: "자월도권역",
    visited: false,
    intro: "서해의 고요한 섬으로 낚시와 해안 산책, 사진 촬영 명소가 많습니다.",
    leisureCourses: ["방파제 낚시", "해안 산책", "일몰 포토"],
    ferryRoute: "인천항 ↔ 자월도",
    travelTime: "약 1시간 50분",
  },
  {
    id: "seungb",
    name: "승봉도",
    region: "자월도권역",
    visited: true,
    intro: "캠핑과 일몰 뷰로 유명한 작은 섬으로 주말 탐험객이 많이 찾습니다.",
    leisureCourses: ["캠핑", "일몰 감상", "해안 트레킹"],
    ferryRoute: "자월도 ↔ 승봉도",
    travelTime: "약 20분",
    bookingLabel: "레저 예약하기",
  },
  {
    id: "ijak",
    name: "대이작도",
    region: "자월도권역",
    visited: false,
    intro: "모래 언덕과 부아산 전망대가 있는 섬으로 하이킹과 인생샷 코스로 인기입니다.",
    leisureCourses: ["풀등 모래섬 산책", "부아산 전망대", "하이킹"],
    ferryRoute: "인천항 ↔ 대이작도",
    travelTime: "약 2시간 10분",
  },
  {
    id: "deokj",
    name: "덕적도",
    region: "덕적도권역",
    visited: true,
    intro: "서해의 대표 레저 섬으로 SUP, 카약, 해안 트레킹이 모두 가능한 탐험 허브입니다.",
    leisureCourses: ["SUP 체험", "카약", "덕적 해안 트레킹"],
    ferryRoute: "인천항 ↔ 덕적도",
    travelTime: "약 1시간 30분",
    bookingLabel: "레저 예약하기",
  },
  {
    id: "soya",
    name: "소야도",
    region: "덕적도권역",
    visited: false,
    intro: "덕적도 인근의 작은 섬으로 조용한 해변과 낚시를 즐기기 좋습니다.",
    leisureCourses: ["낚시", "해변 산책", "사진 촬영"],
    ferryRoute: "덕적도 ↔ 소야도",
    travelTime: "약 15분",
  },
  {
    id: "mungap",
    name: "문갑도",
    region: "덕적도권역",
    visited: false,
    intro: "덕적도권의 작은 섬으로 미니멀한 탐험과 해안 산책에 적합합니다.",
    leisureCourses: ["해안 산책", "낚시", "조용한 휴식"],
    ferryRoute: "덕적도 ↔ 문갑도",
    travelTime: "약 10분",
  },
  {
    id: "gureop",
    name: "굴업도",
    region: "덕적도권역",
    visited: false,
    intro: "덕적도 주변의 작은 섬으로 어촌 풍경과 바다 전망을 가까이에서 즐길 수 있습니다.",
    leisureCourses: ["마을 산책", "낚시", "일출 감상"],
    ferryRoute: "덕적도 ↔ 굴업도",
    travelTime: "약 10분",
  },
];

export const ISLAND_MAP: Record<string, IslandInfo> = Object.fromEntries(
  ISLANDS.map((island) => [island.id, island]),
);

export function getIslandStats() {
  // Deprecated: prefer getIslandVisitStats() from @/lib/user-profile
  const visited = ISLANDS.filter((i) => i.visited).length;
  return { visited, total: ISLANDS.length, percent: Math.round((visited / ISLANDS.length) * 100) };
}
